### PR TITLE
Removing IPackageController code

### PR DESCRIPTION
**Pull request by thriuin**
Removing code that does not appear to be used and is interfering with rendering the read package page on our web site at open.canada.ca

### CODE REVIEW

**Comment by wardi** [comment]
interesting that it only fails on more recent ckan versions. @amercader the `after_show` code is interfering with our custom schema (we have a language field at the resource level) do you know why it's implemented this way and not with a helper and an overridden resource template?

**Comment by amercader** [comment]
@wardi as this is a "generic" extension I didn't want to override the templates as users might have already done so, but if necessary I'm willing to consider it.

In theory `after_show` hooks are called in succession so if your extension if loaded after `dcat` can you not modify the data_dict according to your needs?

**Comment by wardi** [comment]
@amercader this PR was supposed to only include 5ababd0 we can open a new one.

**Comment by thriuin** [comment]
Ah, my bad, I merged in those last 2 commits yesterday - they shouldn't be there.

**Pull request closed without merging**
