### PR TITLE
Make read keywords re-usable

### PR DESCRIPTION
**Pull request by seitenbau-govdata**
* Extract read keywords into function in RDFProfile to make it re-usable

### CODE REVIEW

**Comment by seitenbau-govdata** [comment]
@metaodi and @amercader ,

has one of you some time to review, please? It was only a small re-factoring (moving code) in one file. Thanks in advance.

**Comment by seitenbau-govdata** [comment]
@metaodi and @amercader ,

we also need a new release of the plugin. 😊 And would it be possible to have regular releases? It makes the release of our plugins and the usage by other parties much more easier if we can point to a official release in the requirements.txt instead using self created enriched installation packages. If you have no time (as I assume) we could help and have a look at this and release new version from time to time. 😉

**Comment by metaodi** [comment]
@seitenbau-govdata merged, thanks for this refactoring. I agree on having regular releases, that's why I maintain the CHANGELOG file. I'm currently on vacation, so I could only create a release next week. I guess it would be no problem for you to become maintainers as well. Since this is @amercader's baby, he should decide.

**Comment by seitenbau-govdata** [comment]
@metaodi Many thanks for merging it so fast and this either in your vacation. 😮 I think you know that you really don't have to do this. Anyway I'm happy that I can tick off the point in our to-do list now. 😄 But I hope you will enjoy your remaining holidays. 🌅 Cheers.

**Comment by metaodi** [comment]
@seitenbau-govdata don't worry, all good here 😎

**Comment by amercader** [comment]
@seitenbau-govdata how do you feel about becoming a maintainer as @metaodi suggested? You are obviously heavy users of the extension and have contributed regularly to it. 

This is a pretty mature extension so there won't be a huge workload attached and you could help review incoming PRs and make releases if needed.

No pressure, just let me know if you are interested

**Comment by seitenbau-govdata** [comment]
@amercader Yes, it's fine for me. Do I have to know something special before starting with the work, such as before doing a merge or release a new version?

**Comment by metaodi** [comment]
@seitenbau-govdata I noted down the steps to do a release in the README: https://github.com/ckan/ckanext-dcat#releases

**Comment by seitenbau-govdata** [comment]
@metaodi Great! Thanks a lot for that. This is very useful!

**Comment by seitenbau-govdata** [comment]
> @seitenbau-govdata how do you feel about becoming a maintainer as @metaodi suggested? You are obviously heavy users of the extension and have contributed regularly to it.
> 
> This is a pretty mature extension so there won't be a huge workload attached and you could help review incoming PRs and make releases if needed.
> 
> No pressure, just let me know if you are interested

@amercader We're ready if you are. 😃

**Comment by amercader** [comment]
@seitenbau-govdata sorry sorry sorry I was meaning to do this ages ago and totally slipped my mind. Can you send me an email (amercadero at Gmail.com)? Just want to check one thing. Thanks!

**Comment by seitenbau-govdata** [comment]
@amercader No problem. You have an e-mail.

**Pull request merged**
