### PR TITLE
Feature/add creator support

### PR DESCRIPTION
**Pull request by hcvdwerf**
### Add Creator Support to DCAT Extension

This PR introduces functionality for managing and displaying creator information in datasets, aligning with the DCAT vocabulary. Key additions include:

- **Creator Fields**: Similar to the publisher, we now support creator metadata fields:
  - `creator_name`: The name of the dataset creator.
  - `creator_email`: The creator's email address.
  - `creator_url`: The homepage or URL related to the creator.
  - `creator_identifier`: A unique identifier for the creator, such as an ORCID or other URI.

- **RDF Serialization/Deserialization**:
  - Updated the RDF serializer to include creator fields in the dataset's RDF output.
  - Ensured proper handling of the new fields during both data import and export.

- **Unit Tests**:
  - Extended existing tests to verify the correct inclusion of the creator in the RDF graph.
  - Added new tests to cover all edge cases for creator metadata, including missing or partial data.

This enhancement aligns with the ongoing efforts to ensure full support for the DCAT-AP 2/3 profiles in CKAN's DCAT extension and improves metadata expressiveness by adding proper attribution for dataset creators.

### CODE REVIEW

**Comment by hcvdwerf** [comment]
@amercader  Do you have time to review this one? Thanks in advance!

**Comment by amercader** [comment]
Thanks for this @hcvdwerf , I have many open fronts but will get to this eventually!

**Review by amercader — COMMENTED** [review]
Sorry @hcvdwerf , forgot to push the green button on these comments. Just some minor things and we are good to go

**Review by hcvdwerf — COMMENTED** [review]
@amercader  Thank you for your comments, @amercader! I’ve made adjustments to the code based on your feedback.

**Comment by amercader** [comment]
Thanks @hcvdwerf , nice one

**Pull request merged**
