### PR TITLE
Add references to each of the parsed access services

### PR DESCRIPTION
**Pull request by seitenbau-govdata**
The references for `dcat:accessService` are missing in the profile `euro_dcat_ap_2`. They are required to enhance the `access_services` in further profiles by adding more fields.

### CODE REVIEW

**Comment by seitenbau-govdata** [comment]
The tests are currently failing. See #250

**Comment by seitenbau-govdata** [comment]
Tests are fine now and the PR is ready for review.

**Comment by seitenbau-govdata** [comment]
I assume @amercader is on vacation. Anyone else have any thoughts about the pull request? They are only minor changes, so if not, the PR will be merged and I will make a new release.

**Comment by amercader** [comment]
I wish! Sorry, just have many open fronts now. This looks good, feel free to do a new release

**Pull request merged**
